import * as z from "zod"

export const ContactSchema = z.object({
  conFirst: z.string().min(1,{message: "Required"}).max(255),
  conMiddle : z.string().optional(),
  conLast: z.string().min(1,{message: "Required"}).max(255),
  conEmail: z.string().optional(),
  conType : z.string().min(1,{message: "Required"}).max(255),
  conPrefix : z.string().optional(),
  conSex:z.string().min(1,{message:"Required"}).max(10),
  conBirthdate : z.string().optional(),
  conCity : z.string().optional(),
  conState : z.string().optional(),
  conZip : z.string().optional(),
  conCountry : z.string().optional(),
  conAddress : z.string().optional(),
  conAddress2 : z.string().optional(),
  conAddress3 : z.string().optional(),
  conNotes : z.string().optional(),
  phoneNumber : z.any(),
  conOrg : z.string().optional(),
  conSpeakSpanish : z.string().optional(),
  conDoNotList : z.boolean().optional(),
  conInactivated : z.string().optional(),
})


export const DefContactSchema = z.object({
  conFirst: z.string().min(1,{message: "First Name is required"}).max(255),
  conMiddle : z.string().optional(),
  conLast: z.string().min(1,{message: "Last Name is required"}).max(255),
  conEmail: z.string().optional(),
  conType : z.string().min(1,{message: "Contact Type is required"}).max(255),
  conPrefix : z.string().optional(),
  conSex:z.string().min(1,{message:"Gender is required"}).max(10),
  conBirthdate : z.string().optional(),
  conCity : z.string().optional(),
  conState : z.string().optional(),
  conZip : z.string().optional(),
  conCountry : z.string().optional(),
  conAddress : z.string().optional(),
  conAddress2 : z.string().optional(),
  conAddress3 : z.string().optional(),
  conNotes : z.string().optional(),
  phoneNumber : z.any(),
  conOrg : z.string().optional(),
  conSpeakSpanish : z.string().optional(),
  conDoNotList : z.boolean().optional(),
  conInactivated : z.string().optional(),
  dcStartDate : z.string().optional(),
  dcEndDate : z.string().optional(),
})
