import * as z from "zod"
export const DefendantSchema = z.object({
    defSex: z.string().optional(),
    defFirst: z.string().min(1, { message: "First Name is required" }).max(255),
    defLast: z.string().min(1, { message: "Last Name is required" }).max(255),
    defMiddle: z.string().optional(),
    defNickname: z.string().optional(),
    defLiteracyNotes: z.string().optional(),
    defNotes: z.string().optional(),
    defDOBapprox: z.boolean().optional(),
    defMexicanBirthState: z.string().optional(),
    defMigrationDate: z.string().optional(),
    defMigrationApprox: z.boolean().optional(),
    defHasImpairment: z.boolean().optional(),
    defBirthdate: z.string().optional(),
    defSchoolYearsTotal: z.string().optional(),
    // defLiterateNotes: z.string().optional(),
    defWorkNotes: z.string().optional(),
    // defChargedCountry: z.string().optional(),
    defChargedState: z.string().optional(),
    defChargedCounty: z.string().optional(),
    defIsFederal: z.boolean().optional(),
    defFederalDistrict: z.string().optional(),
    defSpeakEnglish: z.string().optional(),
    defLiterateEnglish: z.string().optional(),
    defLiterateSpanish: z.string().optional(),
    defSpeakSpanish: z.string().optional(),
    defSpeakOtherLanguage: z.string().optional(),
    // alias:z.any().optional(),
    // schoolType: z.string().optional(),
    // schoolName: z.string().optional(),
    // schoolAddress: z.string().optional(),
    // schoolCity: z.string().optional(),
    // schoolState: z.string().optional(),
    // schoolCountry: z.string().optional(),
    // schoolYearStarted: z.string().optional(),
    // schoolYearLeft: z.string().optional(),
    // ImpairmentType : z.string().optional(),
    // ImpDetermined : z.string().optional(),
    // ImpairmentDoctor : z.string().optional(),
    // impDateDiagnosed : z.string().optional(),
    // ImpairmentDescription : z.string().optional(),
    defPrisonID :  z.any(),
    defLevelInvolvement:z.string().optional(),
    defAsssignConsulate:z.string().optional(),
    defDateArrest: z.any(),
    defProgramAttorney : z.any(),
})